AWSTemplateFormatVersion: "2010-09-09"
Description: "Risk Assessment System with EKS, ECS, S3, Step Functions, and Lambda."

Parameters:
  EKSClusterName:
    Type: String
    Default: "RiskAssessmentEKSCluster"

  NodeInstanceType:
    Type: String
    Default: "t2.micro"

  ECSClusterName:
    Type: String
    Default: "RiskAssessmentECSCluster"

  ECRStreamlitImageURI:
    Type: String
    Description: "ECR Image URI for the Streamlit web app"

  ECRModelImageURI:
    Type: String
    Description: "ECR Image URI for the Risk Assessment Model"

Resources:

  # --- VPC ---
  RiskAssessmentVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref RiskAssessmentVPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RiskAssessmentVPC
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs "" ]

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RiskAssessmentVPC
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 1, !GetAZs "" ]

  # --- EKS ---
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      RoleArn: !GetAtt EKSRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2

  # --- EKS Node Group ---
  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: "RiskAssessmentNodeGroup"
      NodeRole: !GetAtt EKSNodeRole.Arn
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      InstanceTypes:
        - !Ref NodeInstanceType
      ScalingConfig:
        MinSize: 2
        MaxSize: 5
        DesiredSize: 3

  EKSNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  # --- S3 Bucket ---
  RiskAssessmentS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "risk-assessment-data"

  # --- IAM for Lambda ---
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "Lambda-S3-StepFunctions-Access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                  - "states:StartExecution"
                  - "events:PutEvents"
                Resource: "*"

  # --- Lambda (S3 Trigger for Step Function) ---
  S3UploadTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "TriggerStepFunctionOnUpload"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          def lambda_handler(event, context):
              sfn_client = boto3.client('stepfunctions')
              for record in event['detail']['requestParameters']['objects']:
                  file_key = record['key']
                  response = sfn_client.start_execution(
                      stateMachineArn=os.environ['STEP_FUNCTION_ARN'],
                      input=json.dumps({"bucket": os.environ['BUCKET_NAME'], "file_key": file_key})
                  )
              return {"statusCode": 200, "body": json.dumps(response)}
      Environment:
        Variables:
          STEP_FUNCTION_ARN: !Ref RiskAssessmentStepFunction
          BUCKET_NAME: !Ref RiskAssessmentS3Bucket

  # --- Step Function ---
  RiskAssessmentStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt LambdaExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Risk Assessment Processing Pipeline",
          "StartAt": "Preprocess Data",
          "States": {
            "Preprocess Data": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:::function:PreprocessLambda",
              "Next": "Aggregate Data"
            },
            "Aggregate Data": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:::function:AggregateLambda",
              "Next": "Call Prediction API"
            },
            "Call Prediction API": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:::function:PredictLambda",
              "Next": "Store Results in S3"
            },
            "Store Results in S3": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:::function:StoreResultsLambda",
              "End": true
            }
          }
        }

  # --- ECS Cluster for Streamlit Web App ---
  StreamlitECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ECS-S3-Access"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource: "*"

  # --- ECS Task Definition for Streamlit ---
  StreamlitTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "StreamlitTask"
      Cpu: "256"
      Memory: "512"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: "streamlit-app"
          Image: !Ref ECRStreamlitImageURI
          Essential: true
          PortMappings:
            - ContainerPort: 8501
          Environment:
            - Name: "S3_BUCKET_NAME"
              Value: !Ref RiskAssessmentS3Bucket
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/ecs/streamlit-app"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"

  # --- ECS Service ---
  StreamlitECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref StreamlitECSCluster
      TaskDefinition: !Ref StreamlitTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2

Outputs:
  StreamlitAppURL:
    Description: "Streamlit Web App URL"
    Value: !Sub "http://${StreamlitECSService}.elb.amazonaws.com:8501"

  S3BucketName:
    Description: "S3 Bucket for Data"
    Value: !Ref RiskAssessmentS3Bucket
