AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for Risk Assessment Model Deployment on EKS using ECR

Parameters:
  AppEnv:
    Description: The environment of the application
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z-]*'
  AppName:
    Description: The name of the application
    Type: String
    MinLength: '1'
  AppVersion:
    Description: The version of the application
    Type: String
    MinLength: '1'

Resources:

# Outputs:
#   VpcId:
#     Description: 'VPC ID'
#     Value: !Ref VPC

#   ECRRepositoryUri:
#     Description: 'URI of the ECR repository'
#     Value: !GetAtt ECRRepository.RepositoryUri

#   EKSClusterName:
#     Description: 'Name of the EKS cluster'
#     Value: !Ref EKSCluster

#   EKSClusterArn:
#     Description: 'ARN of the EKS cluster'
#     Value: !GetAtt EKSCluster.Arn