apiVersion: v1
kind: Service
metadata:
  name: risk-assessment-service-<ENVIRONMENT>
spec:
  type: LoadBalancer  # Expose externally
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: risk-assessment
