name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
      # - name: Build and push Docker image
      #   run: |
      #     cd container
      #     docker build -t risk-assessment-repo .
      #     docker tag risk-assessment-repo:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/risk-assessment-repo:latest
      #     docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/risk-assessment-repo:latest
      #   env:
      #     AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
      #     ARTIFACT_KEY: ${{ env.ARTIFACT_KEY }}
      #     DEPLOYMENT_KEY: ${{ env.DEPLOYMENT_KEY }}
      #     ENVIRONMENT_KEY: ${{ env.ENVIRONMENT_KEY }}
