name: Build and upload Package

run-name: 'Package: ${{ github.ref_name }}_${{ github.run_id }}_${{ github.run_attempt }}'

on:
  push:
    branches: ['master']
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Select the environment'
    #     required: true
    #     default: 'development'
    #     type: choice
    #     options:
    #       - development
    #       - test

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      build-number: ${{ steps.package-default-version.outputs.version }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files and directories for debug
        run: |
          echo "Listing root directory contents:"
          ls -l
          echo "Listing cloudformation directory contents:"
          ls -l cloudformation || echo "cloudformation directory not found"
          echo "Listing forge-files directory contents:"
          ls -l forge-files || echo "forge-files directory not found"

      - id: package-default-version
        name: Get Default Version outputs
        run: echo "version=${{ github.ref_name }}_${{ github.run_id }}_${{ github.run_attempt }}" >> $GITHUB_ENV

      - id: package-create
        name: Package
        run: |
          mkdir -p package
          [ -d cloudformation ] && cp -r cloudformation package/
          [ -d forge-files ] && cp -r forge-files package/
          [ -f README.md ] && cp README.md package/
          echo "Contents of package directory:"
          ls -la package
          cd package
          zip -r ./${{ env.version }}.zip .

      - id: package-upload
        name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.version }}
          path: ${{ env.version }}.zip
          retention-days: 30

      - name: Confirm Upload
        run: |
          echo "Uploaded artifact name: ${{ env.version }}"
          ls -la package