name: Deploy Package

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - test
      build-number:
        description: 'Build number'
        required: true
      # run-id:
      #   description: 'Run ID'
      #   required: true
  
permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }} 

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ARTIFACT_KEY: ${{ vars.ARTIFACT_KEY }}
      DEPLOYMENT_KEY: ${{ vars.DEPLOYMENT_KEY }}
      ENVIRONMENT_KEY: ${{ vars.ENVIRONMENT_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Log build number and run ID
      #   run: echo "Downloading artifact with name ${{ github.event.inputs.build-number }} from run ID ${{ github.event.inputs.run-id }}"

      # - name: Wait for Artifact to be Available
      #   run: sleep 30

      - name: Download Artifact Manually
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: ${{ secrets.ACTIONS_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/jaingit1/risk-assessment-medical-stop-loss/actions/artifacts" \
            | jq -r '.artifacts[0].id')

          curl -L -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
            -o artifact.zip \
            "https://api.github.com/repos/jaingit1/risk-assessment-medical-stop-loss/actions/artifacts/$ARTIFACT_ID/zip"

      - name: Extract Artifact
        run: unzip -o artifact.zip
     
      - name: Set Environment Variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "development" ]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
            echo "ARTIFACT_KEY=${{ vars.ARTIFACT_KEY_DEV }}" >> $GITHUB_ENV
            echo "DEPLOYMENT_KEY=${{ vars.DEPLOYMENT_KEY_DEV }}" >> $GITHUB_ENV
            echo "ENVIRONMENT_KEY=${{ vars.ENVIRONMENT_KEY_DEV }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_TEST }}" >> $GITHUB_ENV
            echo "ARTIFACT_KEY=${{ vars.ARTIFACT_KEY_TEST }}" >> $GITHUB_ENV
            echo "DEPLOYMENT_KEY=${{ vars.DEPLOYMENT_KEY_TEST }}" >> $GITHUB_ENV
            echo "ENVIRONMENT_KEY=${{ vars.ENVIRONMENT_KEY_TEST }}" >> $GITHUB_ENV
          fi